services:
  mariadb:
    restart: unless-stopped

  php:
    restart: unless-stopped
    environment:
      LARAVEL_APP_DEBUG: "false"

  nginx:
    restart: unless-stopped

  caddy:
    image: caddy:${CADDY_TAG}
    container_name: "${PROJECT_NAME}_caddy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./docker-init/data/caddy:/data
      - ./docker-init/config/caddy:/config
    environment:
      - EMAIL=${EMAIL}
      - PROJECT_BASE_URL=${PROJECT_BASE_URL}
    networks:
      - default
    restart: unless-stopped

  crond:
    image: wodby/laravel-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_crond"
    environment:
      CRONTAB: |
        * * * * * php /var/www/html/laravel/artisan schedule:run >> /var/log/cron.log 2>&1
        */5 * * * * php /var/www/html/laravel/artisan queue:work database --tries=1 --max-time=30 --stop-when-empty >> /var/log/cron.log 2>&1
    command: sudo -E crond -f -d 0
    volumes:
      - ./:/var/www/html:cached
    restart: unless-stopped
    depends_on:
      - mariadb
