name: Tests

on:
  push:
    branches:
      - '12-ci-tests'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        working-directory: ./laravel
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
        run: npm install
        run: npm run build --if-present

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        working-directory: ./laravel
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        working-directory: ./laravel
        run: cp .env.example .env

      - name: Generate app key
        working-directory: ./laravel
        run: php artisan key:generate

      - name: Create Database
        working-directory: ./laravel
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        working-directory: ./laravel
        run: vendor/bin/pest
