name: Merge Request
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  call-code-fix-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/workflows/code_fixes.yml

  call-tests-workflow:
    runs-on: ubuntu-latest
    needs: call-code-fix-workflow
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.after }}

      - name: Run Laravel tests
        uses: .github/workflows/laravel.yml
