name: Main
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  call-tests-workflow:
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/laravel.yml
